import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import EarthoProvider from "@/providers/EarthoProvider";
import { ReactQueryTRPCProvider } from "@/providers/ReactTQueryTRPCProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
// Tell react that we are in a test environment
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
          <ReactQueryTRPCProvider>{children}</ReactQueryTRPCProvider>{" "}
      </body>
    </html>
  );
}
